net-il-mio-fotoalbum/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using net_il_mio_fotoalbum.Database;
using net_il_mio_fotoalbum.Models.DatabaseModels;
using net_il_mio_fotoalbum.Models;
using Microsoft.AspNetCore.Authorization;

namespace net_il_mio_fotoalbum.Controllers
{
    [Authorize(Roles = "ADMIN,USER")]
    public class CategoryController : Controller
    {
        
        private IRepository<Category, CategoryFormModel> _repositoryCategory;


        public CategoryController(IRepository<Category, CategoryFormModel> repositoryCategory)
        {            
            _repositoryCategory = repositoryCategory;
        }
        // GET: CategoryController
        public ActionResult Index()
        {
            List<Category> categories = _repositoryCategory.GetAll();

            return View("Index", categories);
        }

        // GET: CategoryController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CategoryController/Create
        public ActionResult Create()
        {
            return View("Create");
        }

        // POST: CategoryController/Create
        [Authorize(Roles = "ADMIN")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CategoryFormModel formModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View("Create", formModel);
                }
                bool result = _repositoryCategory.AddEntity(formModel);
                if (!result)
                {
                    string message = "There was a problem in adding the category to the database";
                    var errorModel = new ErrorViewModel
                    {
                        //ErrorMessage = $"An error occurred: {ex.Message}",
                        ErrorMessage = message,
                        RequestId = HttpContext.TraceIdentifier
                    };
                    return View("Error", errorModel);
                }
                return RedirectToAction("Index");   
            }
            catch
            {
                return View();
            }
        }

        // GET: CategoryController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CategoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CategoryController/Delete/5
        [Authorize(Roles = "ADMIN")]
        public ActionResult Delete(int id)
        {

            try
            {
                bool result = _repositoryCategory.DeleteEntity(id);
                if (!result)
                {
                    string message = "There was a problem in deleting the category";
                    var errorModel = new ErrorViewModel
                    {
                        ErrorMessage = message,
                        RequestId = HttpContext.TraceIdentifier
                    };
                    return View("Error", errorModel);
                }

                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                string innerException = "";
                if (ex.InnerException != null)
                {
                    innerException = ex.InnerException.ToString();
                }
                var errorModel = new ErrorViewModel
                {
                    ErrorMessage = $"{ex.Message}: {innerException}",
                    RequestId = HttpContext.TraceIdentifier
                };
                return View("Error", errorModel);

            }
        }

        // POST: CategoryController/Delete/5
        /*
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        */
    }
}

net-il-mio-fotoalbum/Controllers/PictureController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using net_il_mio_fotoalbum.Database;
using net_il_mio_fotoalbum.Models;
using net_il_mio_fotoalbum.Models.DatabaseModels;

using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace net_il_mio_fotoalbum.Controllers
{
    [Authorize(Roles = "ADMIN,USER")]
    public class PictureController : Controller
    {
        private IRepository<Picture, PictureFormModel> _repositoryPicture;
        private IRepository<Category, CategoryFormModel> _repositoryCategory;


        public PictureController(IRepository<Picture, PictureFormModel> repositoryPicture, IRepository<Category, CategoryFormModel> repositoryCategory)
        {
            _repositoryPicture = repositoryPicture;
            _repositoryCategory = repositoryCategory;
        }
        // GET: PictureController
        public ActionResult Index()
        {
            try
            {
                List<Picture> pictures = _repositoryPicture.GetAll();
                return View("Index",pictures);

            }
            catch (Exception ex)
            {
                var response = new
                {
                    success = false,
                    message = ex.Message
                };
                return BadRequest(response);
            }
        }

        // GET: PictureController/Details/5
        public ActionResult Details(int id)
        {
            Picture? foundedPicture = _repositoryPicture.GetEntityById(id);

            if(foundedPicture == null)
            {
                var errorModel = new ErrorViewModel
                {
                    ErrorMessage = $"The item with id:{id} was not found!",
                    RequestId = HttpContext.TraceIdentifier
                };
                return View("Error", errorModel);
            }

            return View("Details",foundedPicture);

        }
        [Authorize(Roles = "ADMIN")]
        // GET: PictureController/Create
        public ActionResult Create()
        {
            List<SelectListItem> allCategoriesSelectList = new List<SelectListItem>();
            List<Category> databaseAllCategories = _repositoryCategory.GetAll();

            foreach (Category Category in databaseAllCategories)
            {
                allCategoriesSelectList.Add(
                    new SelectListItem
                    {
                        Text = Category.Name,
                        Value = Category.Id.ToString()
                    });
            }

            PictureFormModel formModel = new PictureFormModel
            {
                Picture = new Picture(),
                Categories = allCategoriesSelectList
            };


            return View("Create", formModel);



        }

        // POST: PictureController/Create
        [Authorize(Roles = "ADMIN")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PictureFormModel formModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {

                    // now I initialize a new empty list
                    List<SelectListItem> allCategoriesSelectList = new List<SelectListItem>();
                    // and I fill it with all the categorys because I want to show them in the form again if the form is not filled well so the user can input them again

                    List<Category> databaseAllCategories = _repositoryCategory.GetAll();

                    foreach (Category Category in databaseAllCategories)
                    {
                        allCategoriesSelectList.Add(
                            new SelectListItem
                            {
                                Text = Category.Name,
                                Value = Category.Id.ToString()
                            });
                    }

                    formModel.Categories = allCategoriesSelectList;

                    return View("Create", formModel);
                }
                bool result = _repositoryPicture.AddEntity(formModel);
                if (!result)
                {
                    string message = "There was a problem in adding the picture to the database";
                    var errorModel = new ErrorViewModel
                    {
                        //ErrorMessage = $"An error occurred: {ex.Message}",
                        ErrorMessage = message,
                        RequestId = HttpContext.TraceIdentifier
                    };
                    return View("Error", errorModel);

                }
                
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                string innerException = "";
                if (ex.InnerException != null)
                {
                    innerException = ex.InnerException.ToString();
                }
                var errorModel = new ErrorViewModel
                {
                    ErrorMessage = $"{ex.Message}: {innerException}",
                    RequestId = HttpContext.TraceIdentifier
                };
                return View("Error", errorModel);

            }           

        }

        // GET: PictureController/Edit/5
        [Authorize(Roles = "ADMIN")]
        public ActionResult Update(int id)
        {
            try
            {
                Picture? pictureToEdit = _repositoryPicture.GetEntityById(id);
                if(pictureToEdit == null)
                {
                    string message = "The picture you are trying to modify has not been found";
                    var errorModel = new ErrorViewModel
                    {
                        //ErrorMessage = $"An error occurred: {ex.Message}",
                        ErrorMessage = message,
                        RequestId = HttpContext.TraceIdentifier
                    };
                    return View("Error", errorModel);
                }
                else
                {
                    List<Category> dbCategoriesList = _repositoryCategory.GetAll();
                    List<SelectListItem> selectListItem = new List<SelectListItem>();
                    foreach(Category category in dbCategoriesList)
                    {
                        selectListItem.Add(new SelectListItem
                        {
                            Value = category.Id.ToString(),
                            Text = category.Name,
                            Selected = pictureToEdit.Categories.Any(categoryAssociated => categoryAssociated.Id == category.Id)
                        });
                    }

                    PictureFormModel model = new PictureFormModel
                    {
                        Picture = pictureToEdit,
                        Categories = selectListItem,
                    };
                    return View("Update",model);
                }

            }
            catch(Exception ex)
            {
                string innerException = "";
                if (ex.InnerException != null)
                {
                    innerException = ex.InnerException.ToString();
                }
                var errorModel = new ErrorViewModel
                {
                    ErrorMessage = $"{ex.Message}: {innerException}",
                    RequestId = HttpContext.TraceIdentifier
                };
                return View("Error", errorModel);

            }
            
        }

        // POST: PictureController/Edit/5
        [Authorize(Roles = "ADMIN")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(int id, PictureFormModel formModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {

                    // now I initialize a new empty list
                    List<SelectListItem> allCategoriesSelectList = new List<SelectListItem>();
                    // and I fill it with all the categorys because I want to show them in the form again if the form is not filled well so the user can input them again

                    List<Category> databaseAllCategories = _repositoryCategory.GetAll();

                    foreach (Category Category in databaseAllCategories)
                    {
                        allCategoriesSelectList.Add(
                            new SelectListItem
                            {
                                Text = Category.Name,
                                Value = Category.Id.ToString()
                            });
                    }

                    formModel.Categories = allCategoriesSelectList;

                    return View("Update", formModel);
                }

                bool result = _repositoryPicture.ModifyEntity(id, formModel);
                if (!result)
                {
                    string message = "There was a problem in updating the picture";
                    var errorModel = new ErrorViewModel
                    {
                        
                        ErrorMessage = message,
                        RequestId = HttpContext.TraceIdentifier
                    };
                    return View("Error", errorModel);
                }

                return RedirectToAction("Index");

            }
            catch(Exception ex) 
            {
                string innerException = "";
                if (ex.InnerException != null)
                {
                    innerException = ex.InnerException.ToString();
                }
                var errorModel = new ErrorViewModel
                {
                    ErrorMessage = $"{ex.Message}: {innerException}",
                    RequestId = HttpContext.TraceIdentifier
                };
                return View("Error", errorModel);
            }
        }

        // GET: PictureController/Delete/5

net-il-mio-fotoalbum/Views/Shared/_Footer.cshtml
<footer class="d-flex flex-wrap justify-content-between align-items-center px-3">
    <div>
        <span class="text-muted">© 2023 C# Course, Boolean - Experis</span>
    </div>
    <div>
        <span class="text-muted">Francesco Cauzzi</span>
    </div>
</footer>

net-il-mio-fotoalbum/Views/Shared/_Header.cshtml
<header>

<nav class="navbar navbar-expand-lg navbar-light bg-light px-3">
        <a class="navbar-brand" href="@Url.Action("Index","Home")">My Photo Album</a>
    <button class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto gap-2">

            @if(User.IsInRole("ADMIN") || User.IsInRole("USER"))
            {
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle"
                    href="#"
                    id="navbarDropdown"
                    role="button"
                    data-bs-toggle="dropdown"
                    aria-haspopup="true"
                    aria-expanded="false">
                    Actions
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="@Url.Action("Index","Picture")">See all pictures</a>
                    <div class="dropdown-divider"></div>
                            @if (User.IsInRole("ADMIN"))
                            {
                    <a class="dropdown-item" href="@Url.Action("Create","Picture")">Add a picture</a>
                                
                    <div class="dropdown-divider"></div>
                            }

                    <a class="dropdown-item" href="@Url.Action("Index","Category")">See all categories</a>
                    <div class="dropdown-divider"></div>
                    @if (User.IsInRole("ADMIN"))
                    {                           
                    <a class="dropdown-item" href="@Url.Action("Create","Category")">Add a category</a>
                    <div class="dropdown-divider"></div>
                     }
                </div>                    
            </li>
                }
                
            @*Authentication*@
            <li>
                <partial name="_LoginPartial" />
            </li>
        </ul>
        @if (User.IsInRole("ADMIN"))
        {
            <div class="ms-auto">
                <strong>ADMIN</strong>
            </div>
        }
        @if (User.IsInRole("USER"))
        {
            <div class="ms-auto">
                <strong>USER</strong>
            </div>
        }
           
    </div>
</nav>
</header>

net-il-mio-fotoalbum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - net_il_mio_fotoalbum</title>
    @*
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    *@
    @*Bootstrap version 5.3*@
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    @*compiled css from site.scss*@
    <link rel="stylesheet" href="~/css/compiled/site.css" asp-append-version="true" />
    @*Font Awesome via CDN*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    @*
    <link rel="stylesheet" href="~/net_il_mio_fotoalbum.styles.css" asp-append-version="true" />
    *@
</head>
<body>
    @*Header*@
    @await Html.PartialAsync("_Header")


    
    <main role="main" class="pb-3">
        <div class="__main-sub-ctn container pt-2">
            @RenderBody()

        </div>
    </main>
    

    @*Footer*@
    @await Html.PartialAsync("_Footer")
   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    *@
    @*Bootstrap version 5.3*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>